version: '3.6'

services:
  db:
    container_name: nerdstore
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nerdstore
    ports:
      - 5400:5432 # portas <host>:<container>
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
    db-data:
      name: nerdstore
      driver: local

